
" Pathogen plugin
execute pathogen#infect()

" Don't Behave like vi
set nocompatible                                      

syntax on
filetype plugin indent on

" Searching options
set incsearch                            
set showmatch                              
set smartcase                               
set ignorecase                               
set hlsearch  

" set background=dark

" allow to bg unsaved buffers, etc
set hidden      

" always show status line
set laststatus=2

" show normal etc command
set showcmd              


" proper backspacing
set backspace=indent,eol,start      

" show cursor position
set ruler                                          

" 0 prefixed numbers are still decimal
set nrformats-=octal               

" wraps between word
set linebreak

set scrolloff=1 

" Indentation Options
set autoindent
set smartindent
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4

"round > and < to multiples of shiftwidth
set shiftround

" Fixes slow 0 inserts (all three)
set timeout                      
set timeoutlen=1000
set ttimeoutlen=100

" line Number
set number

" no annoying swap file
set noswapfile

let mapleader=","

" mappings
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
nnoremap <C-c> :w<CR><C-z>
nnoremap <C-x> :w<CR>

" quit highlighting mode
nnoremap <leader><space> :noh<cr>

" Esy indentation
nnoremap <tab> >>
nnoremap <s-tab> <<

" abbreviations 
cnoreabbrev W w
cnoreabbrev Wq wq
cnoreabbrev WQ wq
cnoreabbrev wQ wq
cnoreabbrev Q! q!
