" MY VIMRC

" Calling Pathogen plugin
execute pathogen#infect()
    
" Use only Vim mode
set nocompatible

set fileencoding=utf-8
set encoding=utf-8

set backspace=indent,eol,start

" Shows multi key commands
set showcmd

" shell setting
set shell=/bin/zsh

" Setting Color Scheme
set background=dark
colorscheme solarized

" Understanding filetypes
filetype on
filetype indent on
filetype plugin on

syntax enable

" gives the line number
set number
set numberwidth=2

" Smart indentation
set smartindent

" Rounds indent according to the shiftwidth
set shiftround

" Wrap condition
set linebreak

" Search specifications 
set hlsearch
set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch

" Window settings
set winwidth=84
set winheight=5
set winminheight=5
set winminwidth=20
set winheight=999

" Visual warning
set visualbell

" Disabling swap file
set noswapfile

" Tab settings
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4

set scrolloff=5

" Shows option when using tab completion for cmd line commands
set wildmenu

" Personalised status line
set statusline=%F\ line:%l/%L\ col:%c\ %y\ %r

" Makes Line numbers visible
highlight LineNr ctermfg=blue ctermbg=black

" Status line always visible
set laststatus=2

" MY MAPPINGS
let mapleader=','

nnoremap <C-n> :NERDTreeToggle<CR>
nnoremap <leader>nh :noh<CR>

" Mappings for indenting file having code in different languages
nnoremap <leader>hp :set filetype=html<CR> :w<CR> :set filetype=php<CR> :w<CR> 

" Easily add HTML comments
nnoremap <leader>ch I<!-- <ESC>A --><ESC>^4l

"Easier navigation among windows
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Quick save
nmap <C-x> :w<CR>
imap <C-x> <ESC>:w<CR>a
nmap <C-c> :wq<CR>

" MY AUTO COMMANDS

" Properly indents files when first opened and after saved
autocmd BufRead,BufWritePre *.js normal gg=G
autocmd BufRead,BufWritePre *.php normal gg=G
autocmd BufRead,BufWritePre *.css normal gg=G
autocmd BufRead,BufWritePre *.c normal gg=G
autocmd BufRead,BufWritePre *.html normal gg=G

" Automatically sources the vimrc file on saving
autocmd BufWritePost $MYVIMRC source $MYVIMRC

" MY ABBREVIATIONS

" Command line corrections
cnoreabbrev Wq wq
cnoreabbrev qw wq
cnoreabbrev WQ wq
cnoreabbrev W w
cnoreabbrev Q q

" MY FUNCTIONS

" Not very friendly with the snipmate plugin
" Smartly uses tab for putting tab spaces or autocompletion
"function! SmartTab()
"    let col = col(".") - 1
"    if !col || getline(".")[col - 1] !~ '\k'
"        return "\<Tab>"
"    else
"        return "\<C-n>"
"endfunction

"inoremap <Tab> <C-r>=SmartTab()<CR>
"inoremap <s-Tab> <C-p>
